"""
Day 13 — 三路消融汇总：text-only / audio-only / text+audio（+ 可选：冻结 RoBERTa）

先训练（都用 fusion_day12.py，同一个 LateFusionClassifier、同样的 text_norm / lr / 5 epochs / seed 42 43 44）：
    python src\\fusion_day12.py --modalities text  --tag day13_text     # 约 9 分钟
    python src\\fusion_day12.py --modalities audio --tag day13_audio    # 1 分钟以内（没有 RoBERTa）
    python src\\fusion_day12.py --freeze-text --tag day12_frozen        # 可选，约 2 分钟
    python src\\fusion_day12.py --modalities text --freeze-text --tag day13_text_frozen   # 可选：和上一行凑成 2×2
  （text+audio 那一行直接用 Day 12 的 day12_* 结果，不重跑。
    单模态运行时 fusion_day12 的打印里仍写\"多模态\"、结论里会建议 modality dropout——那是 Day 12 的文案，忽略，以本脚本为准）
再汇总（本脚本只读 results\\ 里的文件，不训练，不碰 test，几十秒）：
    python src\\ablation_day13.py
    python src\\ablation_day13.py --audio-tag day13_audio_e20          # 如果 audio-only 另跑了更多 epoch 的版本

做的事：
  1. 读每个模型的 {tag}_runs.csv（每个 seed 最佳 epoch 的指标）和 {tag}_dev_probs_s*.npy（逐条概率），
     用概率重算 wF1 核对 runs.csv —— 对得上才说明行顺序没错
  2. 消融表：每个模型 3 seed 的 acc / wF1 / mF1 均值 ± 标准差 + 最佳 epoch；参照行：全猜 neutral、Day 9 音频线性探针
  3. 配对 bootstrap（3 seed 平均版）：每次重采样同一组 dev 下标，两个模型各自 3 个 seed 的 wF1 取平均再相减
     → Δ 的 95% 区间。比 Day 12 只比 seed 42 一对更稳
  4. 各类 F1（3 seed 平均）三个模型并排
  5. 混淆矩阵：三个模型（3 seed 平均、按行归一化）+ \"text+audio − text-only\" 差值矩阵（条数）
     → 回答\"anger / disgust 多对的那几条，原来被错判成了什么\"
  6. 稳定修好 / 稳定改坏的句子：text-only 3 个 seed 都错、text+audio 3 个 seed 都对（以及反过来）
  7. 消融表画成图（checklist 的\"表格截图\"）+ 写 EXPERIMENTS.md
输出：
  results\\day13_ablation.csv / day13_per_class.csv / day13_fixed_broken.csv / day13_summary.json
  results\\day13_ablation_table.png / day13_confusion.png / day13_per_class.png
  EXPERIMENTS.md（项目根目录；如果已有一个不是本脚本生成的同名文件，改写到 results\\EXPERIMENTS_day13.md）
"""
import argparse
import json
import os
import time

# fusion_day10 会 import transformers，所以这两行要在它之前
os.environ.setdefault("HF_HOME", r"F:\hf_cache")
os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS_WARNING", "1")

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, f1_score

from fusion_day10 import AUDIO_MODEL, build_table, load_shared_audio
from roberta_day4 import LABELS, OUT_DIR

K = len(LABELS)
ROOT = OUT_DIR.parent
MARK = "<!-- generated by src/ablation_day13.py -->"

# 不在 results\ 里留逐条概率、只能引用日志数字的参照行
TEXT3 = dict(wf1=[0.6068, 0.6030, 0.6023], acc_mean=0.618, acc_sd=0.003, mf1_mean=0.458, mf1_sd=0.003,
             best_epochs=[2, 3, 3])                       # Day 6，1109 口径
PROBE = dict(acc=0.456, wf1=0.424, mf1=0.270)             # Day 9 音频线性探针（mean13，1 次）
NEUTRAL = dict(acc=0.4233, wf1=0.2518, mf1=0.0850)        # 全猜 neutral，1108 口径


# ================================================================ 小工具
def scores(gold, pred):
    """→ acc / wF1 / mF1 / 各类 F1。labels 固定 0..6，某类一次都没预测时 F1 记 0。"""
    lab = list(range(K))
    return dict(acc=float((gold == pred).mean()),
                wf1=float(f1_score(gold, pred, labels=lab, average="weighted", zero_division=0)),
                mf1=float(f1_score(gold, pred, labels=lab, average="macro", zero_division=0)),
                per_class=f1_score(gold, pred, labels=lab, average=None, zero_division=0))


def wf1_fast(gold, pred):
    """和 sklearn 的 weighted F1 一样，但只用 bincount → bootstrap 里每次 <0.1ms。"""
    cm = np.bincount(gold * K + pred, minlength=K * K).reshape(K, K)
    tp = np.diag(cm).astype(float)
    sup, npred = cm.sum(1), cm.sum(0)
    denom = sup + npred                                     # F1 = 2TP / (2TP + FP + FN) = 2TP / (support + 预测数)
    f1 = np.divide(2 * tp, denom, out=np.zeros(K), where=denom > 0)
    return float((f1 * sup).sum() / sup.sum())


def ms(x, d=4):
    x = np.asarray(x, dtype=float)
    return f"{x.mean():.{d}f} ± {x.std(ddof=1):.{d}f}" if len(x) > 1 else f"{x.mean():.{d}f}"


def md_table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


# ================================================================ 读一个模型的结果
def load_model(tag, gold):
    """→ dict(runs, probs{seed: (N,7)}, epochs, max_epoch) 或 None（文件不在）。"""
    p = OUT_DIR / f"{tag}_runs.csv"
    if not p.exists():
        return None
    runs = pd.read_csv(p)
    probs = {}
    for s in runs.seed:
        f = OUT_DIR / f"{tag}_dev_probs_s{s}.npy"
        if not f.exists():
            print(f"  ⚠️ {tag}：缺 {f.name}")
            return None
        probs[int(s)] = np.load(f)
        assert probs[int(s)].shape == (len(gold), K), f"{f.name} 的 shape {probs[int(s)].shape} ≠ ({len(gold)}, {K})"
    ep_p = OUT_DIR / f"{tag}_epochs.csv"
    epochs = pd.read_csv(ep_p) if ep_p.exists() else None
    # 核对：用逐条概率重算的 wF1 应该和训练时记的 runs.csv 一样（行顺序错了这里会对不上）
    for r in runs.itertuples():
        w = scores(gold, probs[int(r.seed)].argmax(1))["wf1"]
        if abs(w - r.dev_wf1) > 1e-3:
            print(f"  ⚠️ {tag} seed {r.seed}：概率重算 wF1 {w:.4f} ≠ runs.csv {r.dev_wf1:.4f}（行顺序不对？被覆盖过？）")
    return dict(runs=runs, probs=probs, epochs=epochs,
                max_epoch=int(epochs.epoch.max()) if epochs is not None else None)


def paired_boot_mean(gold, probs_a, probs_b, n=2000, seed=0):
    """3 seed 平均版的配对 bootstrap：每次抽同一组下标，Δ = mean_s wF1(a_s) − mean_s wF1(b_s)。
    同时覆盖了\"换一批 dev 句子\"的噪声，又不只靠某一个 seed。"""
    rng = np.random.default_rng(seed)
    ya = [p.argmax(1) for p in probs_a]
    yb = [p.argmax(1) for p in probs_b]
    N = len(gold)

    def delta(idx):
        g = gold[idx]
        return np.mean([wf1_fast(g, y[idx]) for y in ya]) - np.mean([wf1_fast(g, y[idx]) for y in yb])

    obs = delta(np.arange(N))
    diffs = np.array([delta(rng.integers(0, N, N)) for _ in range(n)])
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    return dict(diff=float(obs), lo=float(lo), hi=float(hi), p_le0=float((diffs <= 0).mean()), n=n)


# ================================================================ main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--text-tag", default="day13_text")
    ap.add_argument("--audio-tag", default="day13_audio")
    ap.add_argument("--mm-tag", default="day12")
    ap.add_argument("--frozen-tag", default="day12_frozen", help="可选；文件不在就跳过这一行")
    ap.add_argument("--text-frozen-tag", default="day13_text_frozen", help="可选；冻结 RoBERTa 的 text-only")
    ap.add_argument("--bootstrap", type=int, default=2000)
    ap.add_argument("--n-examples", type=int, default=12, help="打印多少条\"稳定修好\"的句子")
    a = ap.parse_args()
    t0 = time.time()

    # ---------- dev 表（行顺序 = fusion_day12 存概率时的顺序）----------
    print("========== 数据 ==========")
    dev_df, _, _ = build_table("dev", AUDIO_MODEL, load_shared_audio(), verbose=False)
    gold = dev_df["label"].to_numpy()
    support = np.bincount(gold, minlength=K)
    shared = dev_df["shared_audio"].to_numpy(dtype=bool)
    print(f"  dev {len(gold)} 条；各类：" + " ".join(f"{l} {n}" for l, n in zip(LABELS, support)))

    # ---------- 读各模型 ----------
    print("\n========== 读取各模型的结果 ==========")
    spec = [  # key, tag, 表里的名字, 输入, RoBERTa
        ("text", a.text_tag, "text-only", "text", "fine-tuned"),
        ("audio", a.audio_tag, "audio-only", "audio (wav2vec2, 13 layers)", "—"),
        ("mm", a.mm_tag, "text + audio", "text + audio", "fine-tuned"),
        ("frozen", a.frozen_tag, "text + audio (frozen RoBERTa)", "text + audio", "frozen"),
        ("tfrozen", a.text_frozen_tag, "text-only (frozen RoBERTa)", "text", "frozen"),
    ]
    cmds = dict(text=f"python src\\fusion_day12.py --modalities text --tag {a.text_tag}",
                audio=f"python src\\fusion_day12.py --modalities audio --tag {a.audio_tag}",
                mm="python src\\fusion_day12.py",
                frozen=f"python src\\fusion_day12.py --freeze-text --tag {a.frozen_tag}",
                tfrozen=f"python src\\fusion_day12.py --modalities text --freeze-text --tag {a.text_frozen_tag}")
    M = {}
    for key, tag, name, inp, enc in spec:
        m = load_model(tag, gold)
        if m is None:
            if key in ("frozen", "tfrozen"):
                print(f"  （可选）{tag} 不在，跳过。要加这一行：{cmds[key]}")
                continue
            raise SystemExit(f"  ❌ 找不到 results\\{tag}_runs.csv / _dev_probs_s*.npy，先跑：{cmds[key]}")
        m.update(tag=tag, name=name, inp=inp, enc=enc)
        M[key] = m
        print(f"  {name:28s} ← {tag}_*  seeds {list(m['probs'])}  最佳 epoch {m['runs'].best_epoch.tolist()}"
              f"（共 {m['max_epoch']} epochs）")
    seeds_ok = all(list(M[k]["probs"]) == list(M["mm"]["probs"]) for k in ("text", "audio"))
    if not seeds_ok:
        print("  ⚠️ 三个模型的 seed 不一样，后面\"3 seed 平均\"的比较不完全对称")

    # Day 6 文本基线（TextClassifier）在同一批 1108 条上的概率，只有 seed 42
    d6 = None
    p6 = OUT_DIR / "day6_dev_probs.npy"
    if p6.exists():
        d6 = np.load(p6)[dev_df["row_csv"].to_numpy()]
        print(f"  Day 6 text-only（TextClassifier）seed 42：day6_dev_probs.npy[row_csv] → wF1 "
              f"{scores(gold, d6.argmax(1))['wf1']:.4f}（应为 0.6065）")

    # ================================================================ 1. 消融表
    print("\n========== 1. 消融表（dev 1108；每个 seed 取 dev wF1 最高的 epoch；均值 ± 标准差）==========")
    rows = []
    for key, m in M.items():
        r = m["runs"]
        rows.append(dict(key=key, model=m["name"], input=m["inp"], roberta=m["enc"], n_seeds=len(r),
                         acc_mean=r.dev_acc.mean(), acc_sd=r.dev_acc.std(ddof=1),
                         wf1_mean=r.dev_wf1.mean(), wf1_sd=r.dev_wf1.std(ddof=1),
                         mf1_mean=r.dev_mf1.mean(), mf1_sd=r.dev_mf1.std(ddof=1),
                         wf1_seeds=" ".join(f"{x:.4f}" for x in r.dev_wf1), best_epochs=str(r.best_epoch.tolist()),
                         wf1_no_shared=(r.dev_wf1_no_shared.mean() if "dev_wf1_no_shared" in r else np.nan)))
    abl = pd.DataFrame(rows)
    ref_rows = [
        ("text-only · TextClassifier (Day 6, n=1109)", f"{TEXT3['acc_mean']:.3f} ± {TEXT3['acc_sd']:.3f}",
         ms(TEXT3["wf1"]), f"{TEXT3['mf1_mean']:.3f} ± {TEXT3['mf1_sd']:.3f}", str(TEXT3["best_epochs"])),
        ("audio linear probe (Day 9, mean13, 1 run)", f"{PROBE['acc']:.3f}", f"{PROBE['wf1']:.3f}", f"{PROBE['mf1']:.3f}", "—"),
        ("always neutral", f"{NEUTRAL['acc']:.4f}", f"{NEUTRAL['wf1']:.4f}", f"{NEUTRAL['mf1']:.4f}", "—"),
    ]
    print(f"  {'模型':30s} {'acc':>17} {'weighted F1':>17} {'macro F1':>17}  best epochs")
    for r in abl.itertuples():
        print(f"  {r.model:30s} {r.acc_mean:>8.4f} ± {r.acc_sd:.4f} {r.wf1_mean:>8.4f} ± {r.wf1_sd:.4f} "
              f"{r.mf1_mean:>8.4f} ± {r.mf1_sd:.4f}  {r.best_epochs}")
    print("  ---- 参照 ----")
    for nm, acc, w, mf, be in ref_rows:
        print(f"  {nm:30s} {acc:>17} {w:>17} {mf:>17}  {be}")
    abl.to_csv(OUT_DIR / "day13_ablation.csv", index=False)

    # audio-only 是不是欠训练：最佳 epoch 全落在最后一个 epoch → 还在涨，多训几个 epoch 可能更高
    au = M["audio"]
    if au["max_epoch"] and (au["runs"].best_epoch == au["max_epoch"]).all():
        print(f"  ⚠️ audio-only 3 个 seed 的最佳 epoch 都是最后一个（{au['max_epoch']}）→ 可能还没训够。"
              f"它没有 RoBERTa、几秒一个 epoch，可以再跑一次：\n"
              f"     python src\\fusion_day12.py --modalities audio --epochs 20 --tag day13_audio_e20\n"
              f"     python src\\ablation_day13.py --audio-tag day13_audio_e20")
    if au["epochs"] is not None:
        g = au["epochs"].groupby("epoch")[["train_loss", "dev_loss", "dev_wf1"]].mean()
        print("  audio-only 按 epoch（3 seed 平均）：" + "  ".join(
            f"e{e} train {r.train_loss:.3f} / dev {r.dev_loss:.3f} / wF1 {r.dev_wf1:.3f}" for e, r in g.iterrows()))

    # ================================================================ 2. 两两比较
    print(f"\n========== 2. 两两比较（3 seed 平均版配对 bootstrap，{a.bootstrap} 次）==========")
    comps = [("mm", "text", "text+audio vs text-only (what audio adds)"),
             ("mm", "audio", "text+audio vs audio-only (what text adds)"),
             ("text", "audio", "text-only vs audio-only")]
    if "frozen" in M:
        comps.append(("mm", "frozen", "fine-tuned vs frozen RoBERTa (both text+audio)"))
    if "frozen" in M and "tfrozen" in M:
        comps.append(("frozen", "tfrozen", "frozen RoBERTa: text+audio vs text-only (what audio adds)"))
    boots = {}
    for ka, kb, desc in comps:
        if not a.bootstrap:
            break
        pa, pb = list(M[ka]["probs"].values()), list(M[kb]["probs"].values())
        b = paired_boot_mean(gold, pa, pb, n=a.bootstrap)
        sd_a, sd_b = M[ka]["runs"].dev_wf1.std(ddof=1), M[kb]["runs"].dev_wf1.std(ddof=1)
        pooled = float(np.sqrt((sd_a ** 2 + sd_b ** 2) / 2))
        b.update(pooled_sd=pooled, n_sd=abs(b["diff"]) / max(pooled, 1e-9))
        boots[f"{ka}_vs_{kb}"] = b
        inside = b["lo"] <= 0 <= b["hi"]
        print(f"  {desc}")
        print(f"    Δ wF1 {b['diff']:+.4f}，95% 区间 [{b['lo']:+.4f}, {b['hi']:+.4f}]，差值 ≤ 0 的比例 {b['p_le0']:.3f}；"
              f"约 {b['n_sd']:.1f} 个 seed 合并标准差 → {'噪声范围内' if inside or b['n_sd'] < 2 else '站得住'}")
    mt = boots.get("mm_vs_text")

    # ================================================================ 3. 各类 F1
    print("\n========== 3. 各类 F1（每个模型 3 seed 平均）==========")
    pc_rows = []
    pcs = {k: np.array([scores(gold, p.argmax(1))["per_class"] for p in m["probs"].values()]) for k, m in M.items()}
    keys3 = ["text", "audio", "mm"] + [k for k in ("frozen", "tfrozen") if k in M]
    print(f"  {'类别':9s} {'n':>4} " + " ".join(f"{M[k]['name'][:14]:>16}" for k in keys3) + f" {'Δ(T+A − T)':>11}")
    for i, l in enumerate(LABELS):
        row = dict(label=l, support=int(support[i]))
        for k in keys3:
            row[f"{k}_mean"] = round(float(pcs[k][:, i].mean()), 4)
            row[f"{k}_sd"] = round(float(pcs[k][:, i].std(ddof=1)), 4)
        row["delta_mm_text"] = round(row["mm_mean"] - row["text_mean"], 4)
        pc_rows.append(row)
        print(f"  {l:9s} {support[i]:>4d} " + " ".join(
            f"{row[f'{k}_mean']:>8.3f} ± {row[f'{k}_sd']:.3f}" for k in keys3) + f" {row['delta_mm_text']:>+11.3f}")
    pc = pd.DataFrame(pc_rows)
    pc.to_csv(OUT_DIR / "day13_per_class.csv", index=False)
    up = pc.sort_values("delta_mm_text", ascending=False)
    print(f"  加音频后提升最多：{up.label.iloc[0]} {up.delta_mm_text.iloc[0]:+.3f}、{up.label.iloc[1]} "
          f"{up.delta_mm_text.iloc[1]:+.3f}；最差：{up.label.iloc[-1]} {up.delta_mm_text.iloc[-1]:+.3f}")
    small = [f"{r.label}（{r.support} 条）" for r in pc.itertuples() if r.support < 50]
    print(f"  {'、'.join(small)} 样本很少，F1 差 0.1 可能只是两三条的差别")

    # ================================================================ 4. 混淆矩阵
    print("\n========== 4. 混淆矩阵（3 seed 平均条数）==========")
    cms = {k: np.mean([confusion_matrix(gold, p.argmax(1), labels=range(K)) for p in m["probs"].values()], axis=0)
           for k, m in M.items()}
    diff = cms["mm"] - cms["text"]
    print("  text+audio − text-only（行 = 真实类别，列 = 预测类别；对角线 + = 多对了，非对角 − = 少错成那一类）：")
    print("  " + " " * 9 + "".join(f"{l[:7]:>8}" for l in LABELS))
    for i, l in enumerate(LABELS):
        print(f"  {l:9s}" + "".join(f"{diff[i, j]:>+8.1f}" for j in range(K)))
    moves = []
    for i, l in enumerate(LABELS):
        off = [(diff[i, j], LABELS[j]) for j in range(K) if j != i]
        dec = sorted(off)[:2]
        inc = sorted(off, reverse=True)[:1]
        moves.append(dict(label=l, diag=round(float(diff[i, i]), 2),
                          less_confused_with={n: round(float(v), 2) for v, n in dec if v < 0},
                          more_confused_with={n: round(float(v), 2) for v, n in inc if v > 0}))
        print(f"  {l:9s} 对角 {diff[i, i]:+5.1f} 条；少错成 "
              + ("、".join(f"{n} {v:+.1f}" for v, n in dec if v < 0) or "—")
              + "；多错成 " + ("、".join(f"{n} {v:+.1f}" for v, n in inc if v > 0) or "—"))
    neu_col = diff[:, LABELS.index("neutral")]
    print(f"  被预测成 neutral 的条数变化（各真实类别求和，不含 neutral 自己）："
          f"{neu_col.sum() - neu_col[LABELS.index('neutral')]:+.1f}")

    # ================================================================ 5. 稳定修好 / 改坏
    print("\n========== 5. 稳定修好 / 稳定改坏（text-only 和 text+audio 各 3 个 seed）==========")
    t_pred = np.stack([p.argmax(1) for p in M["text"]["probs"].values()])     # (3, N)
    m_pred = np.stack([p.argmax(1) for p in M["mm"]["probs"].values()])
    a_pred = np.stack([p.argmax(1) for p in M["audio"]["probs"].values()])
    m_prob_gold = np.mean([p[np.arange(len(gold)), gold] for p in M["mm"]["probs"].values()], axis=0)
    fixed = (t_pred != gold).all(0) & (m_pred == gold).all(0)
    broken = (t_pred == gold).all(0) & (m_pred != gold).all(0)
    print(f"  稳定修好 {fixed.sum()} 条，稳定改坏 {broken.sum()} 条（净 {fixed.sum() - broken.sum():+d}）")
    print("  按真实类别：" + "  ".join(
        f"{l} +{(fixed & (gold == i)).sum()}/−{(broken & (gold == i)).sum()}" for i, l in enumerate(LABELS)))
    text_col = "text" if "text" in dev_df else "Utterance"

    def mode_label(preds_col):
        return LABELS[np.bincount(preds_col, minlength=K).argmax()]

    ex_rows = []
    for kind, mask in (("fixed", fixed), ("broken", broken)):
        for i in np.where(mask)[0]:
            ex_rows.append(dict(kind=kind, dia=int(dev_df["Dialogue_ID"].iloc[i]), utt=int(dev_df["Utterance_ID"].iloc[i]),
                                speaker=dev_df["Speaker"].iloc[i] if "Speaker" in dev_df else "",
                                text=dev_df[text_col].iloc[i], gold=LABELS[gold[i]],
                                text_pred=mode_label(t_pred[:, i]), mm_pred=mode_label(m_pred[:, i]),
                                audio_pred=mode_label(a_pred[:, i]), audio_right=int((a_pred[:, i] == gold[i]).sum()),
                                mm_p_gold=round(float(m_prob_gold[i]), 3),
                                duration_s=round(float(dev_df["duration_s"].iloc[i]), 2) if "duration_s" in dev_df else None,
                                shared_audio=bool(shared[i])))
    ex = pd.DataFrame(ex_rows)
    if len(ex):
        ex = ex.sort_values(["kind", "mm_p_gold"], ascending=[False, False])
        ex.to_csv(OUT_DIR / "day13_fixed_broken.csv", index=False, encoding="utf-8-sig")
        fx = ex[ex.kind == "fixed"]
        print(f"  稳定修好的句子里，audio-only 自己也判对（≥2/3 seed）的占 {(fx.audio_right >= 2).mean():.0%}"
              if len(fx) else "")
        print(f"  稳定修好的例子（text+audio 对 gold 的平均概率从高到低，前 {a.n_examples} 条）：")
        for r in fx.head(a.n_examples).itertuples():
            print(f"    {f'dia{r.dia}_utt{r.utt}':14s} {r.gold:8s} text→{r.text_pred:8s} audio→{r.audio_pred:8s} "
                  f"p={r.mm_p_gold:.2f}  \"{str(r.text)[:60]}\"")

    # ================================================================ 6. 模态依赖（Day 12 的打乱测试，直接引用）
    mm_runs = M["mm"]["runs"]
    dep = None
    if "shuffled_audio_wf1" in mm_runs:
        sa = (mm_runs.shuffled_audio_wf1 - mm_runs.dev_wf1).to_numpy()
        stt = (mm_runs.shuffled_text_wf1 - mm_runs.dev_wf1).to_numpy()
        dep = dict(shuffle_audio=ms(sa), shuffle_text=ms(stt))
        print(f"\n========== 6. 模态依赖（Day 12 打乱测试）==========\n  打乱音频 {ms(sa)}；打乱文本 {ms(stt)}")
        if "frozen" in M and "shuffled_audio_wf1" in M["frozen"]["runs"]:
            fr = M["frozen"]["runs"]
            fsa = (fr.shuffled_audio_wf1 - fr.dev_wf1).to_numpy()
            dep["frozen_shuffle_audio"] = ms(fsa)
            print(f"  冻结 RoBERTa 时打乱音频 {ms(fsa)}（Day 11 1 epoch 是 −0.091）")

    # ================================================================ 7. 结论 + checklist
    print("\n========== 结论 ==========")
    w = {k: M[k]["runs"].dev_wf1.mean() for k in M}
    concl = [f"audio-only wF1 {w['audio']:.4f}：远高于全猜 neutral（{NEUTRAL['wf1']:.3f}），"
             f"{'高于' if w['audio'] > PROBE['wf1'] else '不高于'} Day 9 线性探针（{PROBE['wf1']:.3f}），"
             f"比 text-only 低 {w['text'] - w['audio']:.3f} → 音频有情绪信息，但单独用远不如文本"]
    if mt:
        sig = not (mt["lo"] <= 0 <= mt["hi"]) and mt["n_sd"] >= 2
        concl.append(f"text+audio vs text-only（同一结构）：Δ wF1 {mt['diff']:+.4f}，bootstrap 95% [{mt['lo']:+.4f}, "
                     f"{mt['hi']:+.4f}]，约 {mt['n_sd']:.1f} 个 seed 标准差 → "
                     + ("加音频的提升站得住" if sig else "加音频的整体提升在噪声范围内"))
    concl.append(f"Day 6 TextClassifier vs 同结构 text-only：{np.mean(TEXT3['wf1']):.4f} vs {w['text']:.4f} → "
                 f"{'融合头结构本身几乎没影响' if abs(np.mean(TEXT3['wf1']) - w['text']) < 0.005 else '结构差别有影响，消融表以同结构那行为准'}")
    concl.append(f"各类：提升最多 {up.label.iloc[0]} {up.delta_mm_text.iloc[0]:+.3f} / {up.label.iloc[1]} "
                 f"{up.delta_mm_text.iloc[1]:+.3f}，最差 {up.label.iloc[-1]} {up.delta_mm_text.iloc[-1]:+.3f}")
    for c in concl:
        print(f"  · {c}")
    checks = {"text-only F1 记录完毕": "text" in M, "audio-only F1 记录完毕": "audio" in M,
              "multimodal F1 记录完毕": "mm" in M}

    # ================================================================ 图
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    try:
        import seaborn as sns
    except ImportError:
        sns = None
        print("  （没装 seaborn，用 matplotlib 画热力图；想用 seaborn：python -m pip install seaborn）")

    def heat(ax, mat, title, fmt, cmap, center=None, vmax=None):
        if sns is not None:
            sns.heatmap(mat, ax=ax, annot=True, fmt=fmt, cmap=cmap, center=center, vmin=None if center is None else -vmax,
                        vmax=vmax, cbar=False, xticklabels=LABELS, yticklabels=LABELS, annot_kws={"size": 7})
        else:
            lim = dict(vmin=-vmax, vmax=vmax) if center is not None else dict(vmin=0, vmax=vmax)
            ax.imshow(mat, cmap=cmap, **lim)
            for i in range(K):
                for j in range(K):
                    ax.text(j, i, format(mat[i, j], fmt), ha="center", va="center", fontsize=7)
            ax.set_xticks(range(K), LABELS); ax.set_yticks(range(K), LABELS)
        ax.set_title(title, fontsize=10); ax.set_xlabel("predicted"); ax.set_ylabel("true")
        ax.tick_params(axis="x", rotation=45, labelsize=8); ax.tick_params(axis="y", rotation=0, labelsize=8)

    # 混淆矩阵 2×2：三个模型按行归一化 + 差值
    fig, axs = plt.subplots(2, 2, figsize=(12, 11))
    for ax, k in zip(axs.flat[:3], ["text", "audio", "mm"]):
        norm = cms[k] / cms[k].sum(1, keepdims=True)
        heat(ax, norm, f"{M[k]['name']} — row-normalised (wF1 {w[k]:.3f}, {len(M[k]['probs'])}-seed mean)",
             ".2f", "Blues", vmax=1.0)
    vmax = max(1.0, float(np.abs(diff).max()))
    heat(axs[1, 1], diff, "text+audio − text-only (utterance counts, 3-seed mean)", "+.1f", "RdBu", center=0, vmax=vmax)
    plt.tight_layout(); plt.savefig(OUT_DIR / "day13_confusion.png", dpi=130); plt.close()

    # 各类 F1 柱状图
    fig, ax = plt.subplots(figsize=(11, 4.2))
    xs = np.arange(K)
    cols = dict(text="tab:red", audio="tab:green", mm="tab:blue", frozen="tab:gray", tfrozen="tab:pink")
    wbar = 0.8 / len(keys3)
    for j, k in enumerate(keys3):
        ax.bar(xs + (j - (len(keys3) - 1) / 2) * wbar, pcs[k].mean(0), wbar, yerr=pcs[k].std(0, ddof=1), capsize=2,
               color=cols[k], alpha=0.85, label=f"{M[k]['name']} ({w[k]:.3f})")
    ax.set_xticks(xs, [f"{l}\n(n={n})" for l, n in zip(LABELS, support)], fontsize=8)
    ax.set_ylabel("dev F1 (3-seed mean ± sd)"); ax.set_title("per-class F1 — ablation"); ax.legend(fontsize=7)
    plt.tight_layout(); plt.savefig(OUT_DIR / "day13_per_class.png", dpi=130); plt.close()

    # 消融表画成图（checklist：\"消融实验表格截图保存\"）
    tbl = [[r.model, r.input, r.roberta, f"{r.acc_mean:.4f} ± {r.acc_sd:.4f}", f"{r.wf1_mean:.4f} ± {r.wf1_sd:.4f}",
            f"{r.mf1_mean:.4f} ± {r.mf1_sd:.4f}", r.best_epochs] for r in abl.itertuples()]
    tbl += [[nm, "", "", acc, w_, mf, be] for nm, acc, w_, mf, be in ref_rows]
    fig, ax = plt.subplots(figsize=(14, 0.32 * len(tbl) + 1.0))
    ax.axis("off")
    t = ax.table(cellText=tbl, colLabels=["model", "input", "RoBERTa", "dev acc", "dev weighted F1", "dev macro F1",
                                          "best epochs"], loc="center", cellLoc="center")
    t.auto_set_font_size(False); t.set_fontsize(9); t.scale(1, 1.5)
    t.auto_set_column_width(col=list(range(7)))                 # 按内容定列宽，长名字不被截断
    for (i, j), c in t.get_celld().items():
        if i == 0:
            c.set_facecolor("#dde3ea"); c.set_text_props(weight="bold")
        elif i > len(abl):
            c.set_facecolor("#f4f4f4")
    note = (f"MELD dev, n = {len(gold)} · {len(M['mm']['probs'])} seeds (42/43/44), best epoch per seed by dev weighted F1 · "
            f"same LateFusionClassifier for all {len(abl)} trained rows · test set untouched")
    eps = {M[k]["name"]: M[k]["max_epoch"] for k in M}
    if len(set(eps.values())) > 1:                                  # 例如 audio-only 训了 20 epochs，其他 5 个
        note += "\nepochs trained: " + ", ".join(f"{n} {e}" for n, e in eps.items())
    if mt:
        note += f"\ntext+audio − text-only: Δ wF1 {mt['diff']:+.4f}, paired bootstrap 95% CI [{mt['lo']:+.4f}, {mt['hi']:+.4f}]"
    ax.set_title("Ablation — MELD 7-class emotion recognition", fontsize=12, weight="bold")
    fig.text(0.5, 0.02, note, ha="center", fontsize=8)
    plt.savefig(OUT_DIR / "day13_ablation_table.png", dpi=150, bbox_inches="tight"); plt.close()
    checks["消融实验表格截图保存（day13_ablation_table.png）"] = (OUT_DIR / "day13_ablation_table.png").exists()

    # ================================================================ EXPERIMENTS.md
    md = [MARK, "# Experiments", "",
          f"_Auto-generated by `src/ablation_day13.py` on {time.strftime('%Y-%m-%d %H:%M')} — re-running overwrites this file._",
          "", "All numbers are on the MELD **dev** split restricted to utterances with audio "
          f"(n = {len(gold)}). The test split has not been used yet. Each configuration is trained with seeds 42 / 43 / 44; "
          "for every seed we keep the epoch with the highest dev weighted F1 and report mean ± sd over seeds.", "",
          "## Setup", "",
          "- Text: `roberta-base`, `<s>` vector, fine-tuned (lr 2e-5), LayerNorm before fusion",
          "- Audio: `facebook/wav2vec2-base` (frozen, pre-extracted), mean-pooled over time for all 13 hidden states, "
          "learnable softmax-weighted layer sum → LayerNorm",
          "- Fusion: concat → Dropout → Linear(·, 256) → ReLU → Dropout → Linear(256, 7); head / layer weights / LN lr 1e-3",
          "- AdamW (wd 0.01), 10% linear warm-up then linear decay, grad clip 1.0, bf16, batch 16, 5 epochs, "
          "no class weights",
          "- Single-modality rows use the **same** `LateFusionClassifier` with one input branch (fusion head input 768)",
          *(["- Epochs trained per row: " + ", ".join(f"{n} {e}" for n, e in eps.items())
              + " (audio-only peaked at the last epoch with 5, so it was re-run longer)"]
            if len(set(eps.values())) > 1 else []), "",
          "## Ablation", "",
          md_table(["model", "input", "RoBERTa", "dev acc", "dev weighted F1", "dev macro F1", "best epochs"],
                   [[f"**{r[0]}**" if r[0] == "text + audio" else r[0], *r[1:]] for r in tbl]), ""]
    if boots:
        md += ["Paired bootstrap over dev utterances (2000 resamples; in each resample both models' "
               "weighted F1 is averaged over their 3 seeds):", "",
               md_table(["comparison", "Δ weighted F1", "95% CI", "Δ / pooled seed sd"],
                        [[d, f"{boots[f'{x}_vs_{y}']['diff']:+.4f}",
                          f"[{boots[f'{x}_vs_{y}']['lo']:+.4f}, {boots[f'{x}_vs_{y}']['hi']:+.4f}]",
                          f"{boots[f'{x}_vs_{y}']['n_sd']:.1f}"] for x, y, d in comps]), ""]
    md += ["## Per-class F1 (3-seed mean)", "",
           md_table(["class", "n", *[M[k]["name"] for k in keys3], "Δ (text+audio − text)"],
                    [[r["label"], r["support"], *[f"{r[f'{k}_mean']:.3f}" for k in keys3], f"{r['delta_mm_text']:+.3f}"]
                     for r in pc_rows]), "",
           "![confusion matrices](results/day13_confusion.png)", "",
           "![per-class F1](results/day13_per_class.png)", ""]
    if dep:
        md += ["## Modality reliance (text + audio, best epoch, 3 seeds)", "",
               f"- Shuffling the audio features across dev utterances changes weighted F1 by {dep['shuffle_audio']}; "
               f"shuffling the text changes it by {dep['shuffle_text']}."]
        if "frozen_shuffle_audio" in dep:
            md += [f"- With RoBERTa frozen, shuffling audio changes weighted F1 by {dep['frozen_shuffle_audio']}."]
        md += [""]
    md += ["## Earlier experiments (seed 42 unless noted)", "",
           "**Class weights, text-only (Day 6, 3 seeds, dev 1109):** none 0.604 ± 0.002 · sqrt 0.598 ± 0.009 · "
           "balanced 0.578 ± 0.009 (weighted F1) → no class weights.", "",
           "**Fusion scale fix and head lr (Day 11, 1 epoch):** text_ln 0.595 · none 0.588 · audio_gain 0.582; "
           "head lr 1e-4 0.573 · 3e-4 0.579 · 1e-3 0.595 · 3e-3 0.582; frozen RoBERTa 0.495 → text_ln, 1e-3, fine-tune RoBERTa.",
           "", "**Audio layer probe (Day 9, logistic regression per wav2vec2 layer):** middle layers (4–10) best; "
           "mean of 13 layers 0.424 weighted F1 ≈ best single layer (layer 8, 0.421).", "",
           "## Commands", "", "```", cmds["text"], cmds["audio"], cmds["mm"]]
    md += [cmds[k] for k in ("frozen", "tfrozen") if k in M]
    md += ["python src\\ablation_day13.py", "```", ""]
    exp = ROOT / "EXPERIMENTS.md"
    if exp.exists() and not exp.read_text(encoding="utf-8").startswith(MARK):
        exp = OUT_DIR / "EXPERIMENTS_day13.md"
        print(f"  已有一个手写的 EXPERIMENTS.md，不覆盖，改写到 {exp}")
    exp.write_text("\n".join(md), encoding="utf-8")

    summary = dict(n_dev=len(gold), ablation=abl.drop(columns=["key"]).to_dict("records"), reference=ref_rows,
                   bootstrap=boots, per_class=pc_rows, confusion_diff_mm_minus_text=diff.round(2).tolist(),
                   confusion_moves=moves, fixed=int(fixed.sum()), broken=int(broken.sum()), modality_reliance=dep,
                   conclusions=concl, checks=checks, tags={k: M[k]["tag"] for k in M},
                   saved_at=time.strftime("%Y-%m-%d %H:%M"))
    (OUT_DIR / "day13_summary.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False, default=str),
                                                encoding="utf-8")
    print(f"\n已保存 results\\day13_ablation.csv / _per_class.csv / _fixed_broken.csv / _summary.json / "
          f"_ablation_table.png / _confusion.png / _per_class.png，以及 {exp.relative_to(ROOT)}（{time.time() - t0:.0f}s）")
    print("\nDay 13 checklist：")
    for k_, v in checks.items():
        print(f"  {'✅' if v else '⚠️'} {k_}")
    print("\nDay 13 完成 ✅" if all(checks.values()) else "\n有 checklist 没达标 ⚠️")


if __name__ == "__main__":
    main()
